In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
from skimage.transform import resize
from skimage.io import imread
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Data Preprocessing

In [3]:
gestures=['hand0','hand1','hand5','hand8','hand13','AIgeneratedHands']
images=[] 
label=[] 
directory='Half-HandGesture\\' 

for i in gestures:    
    path=os.path.join(directory,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3)) 
        images.append(img_resized.flatten())
        label.append(gestures.index(i))
        
final_input=np.array(images)
target=np.array(label)

In [4]:
df=pd.DataFrame(final_input) 
df['Target']=target
x=df.iloc[:,:-1] 
y=df.iloc[:,-1] 

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components=200)
X_pca = pca.fit_transform(x)

In [6]:
X_pca.shape
#2500 is the total number of images, 675000 is calculated by 150*150*3, here there are 67500 values
#To reduce overfitting of the models, here I used PCA to reduce dimensions of the features

(3000, 200)

In [7]:
y.shape

(3000,)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X_pca,y,test_size=0.15,random_state=77,stratify=y)

# SGD

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

In [10]:
sgd= SGDClassifier(loss='log',shuffle=True,random_state=101)
sgd.fit(x_train, y_train)
y_pred_sgd = sgd.predict(x_test) 
y_train_score_sgd=sgd.predict(x_train)

acc_train = accuracy_score(y_train, y_train_score_sgd, normalize=True, sample_weight=None)
acc_test = accuracy_score(y_test, y_pred_sgd, normalize=True, sample_weight=None)

print('Train Accuracy is',acc_train)
print("Test Accuracy is ", acc_test)

Train Accuracy is 0.6129411764705882
Test Accuracy is  0.5377777777777778


In [11]:
print("Classification Report : \n",classification_report(y_test, y_pred_sgd))

Classification Report : 
               precision    recall  f1-score   support

           0       0.45      0.41      0.43        75
           1       0.47      0.36      0.41        75
           2       0.48      0.39      0.43        75
           3       0.50      0.41      0.45        75
           4       0.40      0.67      0.50        75
           5       0.99      0.99      0.99        75

    accuracy                           0.54       450
   macro avg       0.55      0.54      0.53       450
weighted avg       0.55      0.54      0.53       450



In [12]:
from sklearn.metrics import confusion_matrix

In [13]:
cm = confusion_matrix(y_test, y_pred_sgd)

In [14]:
cm

array([[31, 12, 10,  9, 12,  1],
       [15, 27, 10, 11, 12,  0],
       [ 6,  6, 29,  7, 27,  0],
       [11,  4,  6, 31, 23,  0],
       [ 6,  9,  6,  4, 50,  0],
       [ 0,  0,  0,  0,  1, 74]], dtype=int64)

# SVM

In [15]:
from sklearn.svm import SVC

In [16]:
svm = SVC(kernel="sigmoid",gamma=0.5,probability=True)
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.22444444444444445
Train Accuracy is 0.20705882352941177


In [17]:
svm = SVC(kernel="rbf",gamma=0.5,probability=True) 
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.1688888888888889
Train Accuracy is 1.0


In [18]:
svm = SVC(kernel="poly",gamma=0.5,probability=True) 
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.6666666666666666
Train Accuracy is 1.0


In [19]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.51      0.64      0.57        75
           1       0.62      0.61      0.62        75
           2       0.73      0.61      0.67        75
           3       0.59      0.48      0.53        75
           4       0.59      0.65      0.62        75
           5       1.00      1.00      1.00        75

    accuracy                           0.67       450
   macro avg       0.67      0.67      0.67       450
weighted avg       0.67      0.67      0.67       450



In [20]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[48,  6,  3, 11,  7,  0],
       [10, 46,  4,  6,  9,  0],
       [ 8,  6, 46,  4, 11,  0],
       [20,  8,  4, 36,  7,  0],
       [ 8,  8,  6,  4, 49,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# Ramdom Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100, random_state=42)
forest.fit(x_train, y_train)
y_pred = forest.predict(x_test)

y_train_score=forest.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

test_acc = accuracy_score(y_test, y_pred)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.6733333333333333
Train Accuracy is 1.0


In [22]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.63      0.65      0.64        75
           1       0.59      0.60      0.60        75
           2       0.61      0.60      0.60        75
           3       0.61      0.59      0.60        75
           4       0.61      0.60      0.60        75
           5       0.99      1.00      0.99        75

    accuracy                           0.67       450
   macro avg       0.67      0.67      0.67       450
weighted avg       0.67      0.67      0.67       450



In [23]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[49,  8,  4,  9,  5,  0],
       [11, 45,  8,  7,  4,  0],
       [ 2,  6, 45,  8, 13,  1],
       [10,  6,  8, 44,  7,  0],
       [ 6, 11,  9,  4, 45,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# KNN

In [24]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
test_acc = accuracy_score(y_test, y_pred)

y_train_score=knn.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.6577777777777778
Train Accuracy is 0.7968627450980392


In [25]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.60      0.73      0.66        75
           1       0.48      0.68      0.56        75
           2       0.66      0.55      0.60        75
           3       0.72      0.41      0.53        75
           4       0.61      0.57      0.59        75
           5       1.00      1.00      1.00        75

    accuracy                           0.66       450
   macro avg       0.68      0.66      0.66       450
weighted avg       0.68      0.66      0.66       450



In [26]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 13,  3,  2,  2,  0],
       [14, 51,  2,  3,  5,  0],
       [ 5, 11, 41,  2, 16,  0],
       [12, 24,  3, 31,  5,  0],
       [ 6,  8, 13,  5, 43,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# Decision Tree

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
tree = DecisionTreeClassifier(criterion='gini',                               
                                max_depth=10, 
                              random_state=1)
tree.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, random_state=1)

In [29]:
y_pred = tree.predict(x_test)
test_acc = accuracy_score(y_test, y_pred)

y_train_score=tree.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',acc_train)

Test Accuracy is  0.4822222222222222
Train Accuracy is 0.7082352941176471


In [30]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.43      0.36      0.39        75
           1       0.40      0.45      0.42        75
           2       0.44      0.21      0.29        75
           3       0.32      0.57      0.41        75
           4       0.40      0.29      0.34        75
           5       1.00      1.00      1.00        75

    accuracy                           0.48       450
   macro avg       0.50      0.48      0.47       450
weighted avg       0.50      0.48      0.47       450



In [31]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[27, 11,  5, 23,  9,  0],
       [14, 34,  6, 17,  4,  0],
       [ 7, 13, 16, 24, 15,  0],
       [ 6, 16,  5, 43,  5,  0],
       [ 9, 12,  4, 28, 22,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# Ensemble-bagging

In [11]:
from sklearn.ensemble import BaggingClassifier

In [12]:
tree = DecisionTreeClassifier(criterion='entropy', 
                              max_depth=None,
                              random_state=1)

bag = BaggingClassifier(base_estimator=tree,
                        n_estimators=100, 
                        max_samples=1.0, 
                        max_features=1.0, 
                        bootstrap=True, 
                        bootstrap_features=False, 
                        n_jobs=1, 
                        random_state=1)
bag = bag.fit(x_train, y_train)
y_train_pred = bag.predict(x_train)
y_test_pred = bag.predict(x_test)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.6777777777777778
Train Accuracy is 1.0


In [13]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.64      0.57      0.61        75
           1       0.60      0.60      0.60        75
           2       0.60      0.63      0.61        75
           3       0.64      0.64      0.64        75
           4       0.59      0.63      0.61        75
           5       1.00      1.00      1.00        75

    accuracy                           0.68       450
   macro avg       0.68      0.68      0.68       450
weighted avg       0.68      0.68      0.68       450



In [14]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[43, 13,  9,  5,  5,  0],
       [10, 45,  7,  6,  7,  0],
       [ 4,  3, 47,  8, 13,  0],
       [ 6,  6,  7, 48,  8,  0],
       [ 4,  8,  8,  8, 47,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# Boosting- AdaBoost

In [15]:
from sklearn.ensemble import AdaBoostClassifier

In [16]:
adb = AdaBoostClassifier(n_estimators=100, base_estimator=tree,learning_rate=1)
adb.fit(x_train, y_train)
y_test_pred = adb.predict(x_test)

y_train_pred = adb.predict(x_train)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.5022222222222222
Train Accuracy is 1.0


In [17]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.36      0.35      0.35        75
           1       0.38      0.33      0.35        75
           2       0.48      0.40      0.43        75
           3       0.39      0.45      0.42        75
           4       0.42      0.48      0.45        75
           5       1.00      1.00      1.00        75

    accuracy                           0.50       450
   macro avg       0.50      0.50      0.50       450
weighted avg       0.50      0.50      0.50       450



In [18]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[26, 17,  9, 15,  8,  0],
       [19, 25,  7, 13, 11,  0],
       [11,  6, 30, 11, 17,  0],
       [12,  9,  7, 34, 13,  0],
       [ 5,  9, 10, 15, 36,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)

# Gradient Boosting

In [19]:
from sklearn.ensemble import GradientBoostingClassifier

In [20]:
gbc = GradientBoostingClassifier()

gbc.fit(x_train, y_train)
y_test_pred = gbc.predict(x_test)

y_train_pred = gbc.predict(x_train)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.7066666666666667
Train Accuracy is 0.9874509803921568


In [21]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.65      0.53      0.58        75
           1       0.63      0.71      0.67        75
           2       0.69      0.65      0.67        75
           3       0.68      0.68      0.68        75
           4       0.60      0.67      0.63        75
           5       1.00      1.00      1.00        75

    accuracy                           0.71       450
   macro avg       0.71      0.71      0.71       450
weighted avg       0.71      0.71      0.71       450



In [22]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[40, 13,  5,  9,  8,  0],
       [ 4, 53,  5,  6,  7,  0],
       [ 3,  3, 49,  5, 15,  0],
       [ 5,  6, 10, 51,  3,  0],
       [10,  9,  2,  4, 50,  0],
       [ 0,  0,  0,  0,  0, 75]], dtype=int64)