In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
from skimage.transform import resize
from skimage.io import imread
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

# Data Preprocessing

In [3]:
gestures=['hand0','hand1','hand5','hand8','hand13']
images=[] 
label=[] 
directory='Half-HandGesture\\' 

for i in gestures:    
    path=os.path.join(directory,i)
    for img in os.listdir(path):
        img_array=imread(os.path.join(path,img))
        img_resized=resize(img_array,(150,150,3)) 
        images.append(img_resized.flatten())
        label.append(gestures.index(i))
        
final_input=np.array(images)
target=np.array(label)

In [4]:
df=pd.DataFrame(final_input) 
df['Target']=target
x=df.iloc[:,:-1] 
y=df.iloc[:,-1] 

In [5]:
from sklearn.decomposition import PCA
pca = PCA(n_components=200)
X_pca = pca.fit_transform(x)

In [6]:
X_pca.shape
#2500 is the total number of images, 675000 is calculated by 150*150*3, here there are 67500 values
#To reduce overfitting of the models, here I used PCA to reduce dimensions of the features

(2500, 200)

In [7]:
y.shape

(2500,)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(X_pca,y,test_size=0.15,random_state=77,stratify=y)

# SGD

In [9]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

In [10]:
sgd= SGDClassifier(loss='log',shuffle=True,random_state=101)
sgd.fit(x_train, y_train)
y_pred_sgd = sgd.predict(x_test) 
y_train_score_sgd=sgd.predict(x_train)

acc_train = accuracy_score(y_train, y_train_score_sgd, normalize=True, sample_weight=None)
acc_test = accuracy_score(y_test, y_pred_sgd, normalize=True, sample_weight=None)

print('Train Accuracy is',acc_train)
print("Test Accuracy is ", acc_test)

Train Accuracy is 0.5091764705882353
Test Accuracy is  0.408


In [11]:
print("Classification Report : \n",classification_report(y_test, y_pred_sgd))

Classification Report : 
               precision    recall  f1-score   support

           0       0.33      0.35      0.34        75
           1       0.53      0.36      0.43        75
           2       0.35      0.31      0.33        75
           3       0.48      0.53      0.50        75
           4       0.39      0.49      0.44        75

    accuracy                           0.41       375
   macro avg       0.41      0.41      0.41       375
weighted avg       0.41      0.41      0.41       375



In [10]:
from sklearn.metrics import confusion_matrix

In [13]:
cm = confusion_matrix(y_test, y_pred_sgd)

In [14]:
cm

array([[26, 12,  7, 17, 13],
       [24, 27, 10,  9,  5],
       [10,  4, 23, 11, 27],
       [ 6,  4, 13, 40, 12],
       [14,  4, 13,  7, 37]], dtype=int64)

# SVM

In [15]:
from sklearn.svm import SVC

In [16]:
svm = SVC(kernel="sigmoid",gamma=0.5,probability=True)
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.192
Train Accuracy is 0.192


In [17]:
svm = SVC(kernel="rbf",gamma=0.5,probability=True) 
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.20266666666666666
Train Accuracy is 1.0


In [18]:
svm = SVC(kernel="poly",gamma=0.5,probability=True) 
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)

y_train_score=svm.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.5706666666666667
Train Accuracy is 1.0


In [19]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.51      0.57      0.54        75
           1       0.64      0.57      0.61        75
           2       0.67      0.56      0.61        75
           3       0.56      0.52      0.54        75
           4       0.52      0.63      0.57        75

    accuracy                           0.57       375
   macro avg       0.58      0.57      0.57       375
weighted avg       0.58      0.57      0.57       375



In [20]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[43,  4,  4, 17,  7],
       [13, 43,  5,  9,  5],
       [ 8,  5, 42,  2, 18],
       [12,  8,  2, 39, 14],
       [ 8,  7, 10,  3, 47]], dtype=int64)

# Ramdom Forest

In [21]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators=100, random_state=42)
forest.fit(x_train, y_train)
y_pred = forest.predict(x_test)

y_train_score=forest.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

test_acc = accuracy_score(y_test, y_pred)
print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.5893333333333334
Train Accuracy is 1.0


In [22]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.58      0.60      0.59        75
           1       0.62      0.61      0.62        75
           2       0.63      0.59      0.61        75
           3       0.58      0.56      0.57        75
           4       0.54      0.59      0.56        75

    accuracy                           0.59       375
   macro avg       0.59      0.59      0.59       375
weighted avg       0.59      0.59      0.59       375



In [23]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[45,  8,  5,  9,  8],
       [12, 46,  3,  7,  7],
       [ 4,  6, 44,  7, 14],
       [11,  5,  9, 42,  8],
       [ 6,  9,  9,  7, 44]], dtype=int64)

# KNN

In [25]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)

y_pred = knn.predict(x_test)
test_acc = accuracy_score(y_test, y_pred)

y_train_score=knn.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

print("Test Accuracy is ",accuracy_score(y_test, y_pred))
print('Train Accuracy is',acc_train)

Test Accuracy is  0.616
Train Accuracy is 0.7835294117647059


In [26]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.64      0.73      0.68        75
           1       0.51      0.68      0.58        75
           2       0.70      0.59      0.64        75
           3       0.72      0.44      0.55        75
           4       0.60      0.64      0.62        75

    accuracy                           0.62       375
   macro avg       0.63      0.62      0.61       375
weighted avg       0.63      0.62      0.61       375



In [27]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[55, 12,  2,  3,  3],
       [13, 51,  2,  5,  4],
       [ 4,  8, 44,  1, 18],
       [ 9, 23,  3, 33,  7],
       [ 5,  6, 12,  4, 48]], dtype=int64)

# Decision Tree

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [35]:
tree = DecisionTreeClassifier(criterion='gini',                               
                                max_depth=10, 
                              random_state=1)
tree.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10, random_state=1)

In [36]:
y_pred = tree.predict(x_test)
test_acc = accuracy_score(y_test, y_pred)

y_train_score=tree.predict(x_train)
acc_train = accuracy_score(y_train, y_train_score)

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',acc_train)

Test Accuracy is  0.36
Train Accuracy is 0.6301176470588236


In [37]:
print("Classification Report : \n",classification_report(y_test, y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.34      0.27      0.30        75
           1       0.43      0.51      0.46        75
           2       0.44      0.28      0.34        75
           3       0.32      0.31      0.31        75
           4       0.31      0.44      0.36        75

    accuracy                           0.36       375
   macro avg       0.37      0.36      0.36       375
weighted avg       0.37      0.36      0.36       375



In [38]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[20, 13,  6, 12, 24],
       [ 9, 38,  6, 11, 11],
       [ 7, 13, 21, 11, 23],
       [14, 17,  5, 23, 16],
       [ 9,  8, 10, 15, 33]], dtype=int64)

# Ensemble-bagging

In [11]:
from sklearn.ensemble import BaggingClassifier

In [15]:
tree = DecisionTreeClassifier(criterion='entropy', 
                              max_depth=None,
                              random_state=1)

bag = BaggingClassifier(base_estimator=tree,
                        n_estimators=100, 
                        max_samples=1.0, 
                        max_features=1.0, 
                        bootstrap=True, 
                        bootstrap_features=False, 
                        n_jobs=1, 
                        random_state=1)
bag = bag.fit(x_train, y_train)
y_train_pred = bag.predict(x_train)
y_test_pred = bag.predict(x_test)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.6613333333333333
Train Accuracy is 1.0


In [16]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.69      0.61      0.65        75
           1       0.58      0.67      0.62        75
           2       0.69      0.68      0.68        75
           3       0.63      0.67      0.65        75
           4       0.74      0.68      0.71        75

    accuracy                           0.66       375
   macro avg       0.67      0.66      0.66       375
weighted avg       0.67      0.66      0.66       375



In [17]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[46, 10,  7,  7,  5],
       [ 7, 50,  1, 11,  6],
       [ 3, 10, 51,  5,  6],
       [ 6,  8, 10, 50,  1],
       [ 5,  8,  5,  6, 51]], dtype=int64)

# Boosting- AdaBoost

In [18]:
from sklearn.ensemble import AdaBoostClassifier

In [20]:
adb = AdaBoostClassifier(n_estimators=100, base_estimator=tree,learning_rate=1)
adb.fit(x_train, y_train)
y_test_pred = adb.predict(x_test)

y_train_pred = adb.predict(x_train)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.384
Train Accuracy is 1.0


In [21]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.45      0.44      0.45        75
           1       0.37      0.35      0.36        75
           2       0.42      0.39      0.40        75
           3       0.33      0.33      0.33        75
           4       0.36      0.41      0.38        75

    accuracy                           0.38       375
   macro avg       0.39      0.38      0.38       375
weighted avg       0.39      0.38      0.38       375



In [22]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[33, 10, 12,  8, 12],
       [13, 26,  6, 12, 18],
       [ 6, 12, 29, 14, 14],
       [11, 12, 15, 25, 12],
       [10, 11,  7, 16, 31]], dtype=int64)

# Gradient Boosting

In [23]:
from sklearn.ensemble import GradientBoostingClassifier

In [24]:
gbc = GradientBoostingClassifier()

gbc.fit(x_train, y_train)
y_test_pred = gbc.predict(x_test)

y_train_pred = gbc.predict(x_train)

test_acc = accuracy_score(y_test, y_test_pred) 
train_acc= accuracy_score(y_train, y_train_pred) 

print("Test Accuracy is ",test_acc)
print('Train Accuracy is',train_acc)

Test Accuracy is  0.6746666666666666
Train Accuracy is 0.9868235294117647


In [25]:
print("Classification Report : \n",classification_report(y_test, y_test_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.61      0.68        75
           1       0.70      0.64      0.67        75
           2       0.74      0.64      0.69        75
           3       0.65      0.80      0.71        75
           4       0.58      0.68      0.63        75

    accuracy                           0.67       375
   macro avg       0.69      0.67      0.67       375
weighted avg       0.69      0.67      0.67       375



In [26]:
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[46,  8,  4,  9,  8],
       [ 8, 48,  4,  9,  6],
       [ 0,  4, 48,  6, 17],
       [ 1,  4,  4, 60,  6],
       [ 5,  5,  5,  9, 51]], dtype=int64)